### ISSUE TITLE
Localizing StringFormat throws "Binding cannot be changed after it has been used." exception

### ISSUE THREAD

**Issue by TheNetStriker** [XAMLMarkupExtensions/WPFLocalizationExtension#107] opened 2016-08-19 11:34 UTC
I'am trying to localize the StringFormat in a TextBlock:
`
<TextBlock Text="{Binding StringFormat={lex:Loc TextBlock_StringFormat}}"
`
This works very good until I try to change the localisation by setting LocalizeDictionary.Instance.Culture. Then the following exception is thrown:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Binding cannot be changed after it has been used.
   at System.Windows.Data.BindingBase.CheckSealed()
   at System.Windows.Data.BindingBase.set_StringFormat(String value)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   at WPFLocalizeExtension.Extensions.LocExtension.ResourceChanged(DependencyObject sender, DictionaryEventArgs e)

How can I solve this problem?

**Comment by SeriousM** [comment] 2016-08-19 13:08
Honestly I have too few information from you.
Could you please try to isolate the issue into a small example project so we can check the issue?
Thank you

**Comment by TheNetStriker** [comment] 2016-08-19 15:32
I've created a small demo application and uploaded it to my Google Drive: https://drive.google.com/open?id=0B130Kflx3WntU1Q1OGlHTFZfNEU

What I'm trying to do is set a localized string in the StringFormat Property inside a Binding.

**Comment by jongleur1983** [comment] 2016-09-14 16:38
Hi.
Stumbled over the same issue in the last days (and it's damn hard to debug if you don't know where it could crash.
I'm going to reproduce it today, but I'm not yet sure it's a WPFLocalizationExtension-only issue. It might be an issue with any bindings in triggers in styles in WPF affected by Culture changes.

Going to investigate it today.
A quick look into the demo of @TheNetStriker shows something different than I discovered, probably with the same source problem.

**Comment by jongleur1983** [comment] 2016-09-14 20:05
in fact the issue seems to be a duplicate of #85 (as @SeriousM said there)

**Comment by deakjahn** [comment] 2018-02-15 11:13
This shouldn't have been closed. The problem is still there and no, it's not a duplicate of the workaround suggested in #85. In my case, it has nothing to do with styles.

**Comment by SeriousM** [comment] 2018-02-16 19:23
So then please provide a small sample so I can debug it. Thank you

**Comment by konne** [comment] 2018-09-08 09:00
I believe it's closed because of no sample was added

**Comment by mindaugasveb** [comment] 2019-01-09 07:18
Issue can be reproduced with the following example.

`                                    <TextBlock>
                                        <TextBlock.Text>
                                            <MultiBinding StringFormat="{lex:Loc SomeString}">
                                                <Binding Path="SomeValue"/>
                                            </MultiBinding>
                                        </TextBlock.Text>
                                    </TextBlock>`

Exception is thrown after changing the language.

**Comment by konne** [comment] 2019-01-09 08:20
@mindaugasveb thanks, I will reopen this issue and will have a look this week, I work already on this package for other small things

**Comment by stijndp** [comment] 2019-01-09 10:53
Thanks for checking konne.
TheNetStriker's solution is still available and gives the error in the included version and the latest version of the lib.

**Comment by Karnah** [comment] 2019-02-06 13:49
Good day. I had the same problem. I used next Binding:

``` xaml
<TextBlock.Text>
    <MultiBinding StringFormat="{0} {1}">
        <Binding Path="Amount" />
        <Binding Source="{lex:LocTextUpper Rub}" />
    </MultiBinding>
</TextBlock.Text>
```
I changed to use this with Proxy:

``` xaml
<lex:LocProxy x:Name="RubStringProxy" Source="{Binding Source='Rub'}" />
...
<TextBlock.Text>
    <MultiBinding StringFormat="{0} {1}">
        <Binding Path="Amount" />
        <Binding ElementName="RubStringProxy" Path="Result" Converter="{c:ToUpperConverter}" />
    </MultiBinding>
</TextBlock.Text>
```

It is more incomprehensible, but it's working.

**Comment by konne** [comment] 2020-05-12 11:35
@Karnah this doesn't solve the issue if you like to have a stringformat per language to have for examples different positions of the parameter
I will close that issue please follow up the discussion here: #186

**Closed by konne** 2020-05-12 11:35 UTC
