### ISSUE TITLE
Exception thrown on LocalizeDictionary.Instance.Culture Changed

### ISSUE THREAD

**Issue by AlastairCodd** [XAMLMarkupExtensions/WPFLocalizationExtension#194] opened 2019-05-20 16:16 UTC
On changing the culture, I'm getting an exception with the following stack trace: 
`   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke[TResult](Func``1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke[TResult](Func``1 callback)
   at XAMLMarkupExtensions.Base.DependencyObjectHelper.GetValueSync[T](DependencyObject obj, DependencyProperty property)
   at WPFLocalizeExtension.Engine.LocalizeDictionary.GetProvider(DependencyObject obj)
   at WPFLocalizeExtension.Providers.ParentChangedNotifierHelper.GetValue[T](DependencyObject target, Func``2 getFunction)
   at WPFLocalizeExtension.Engine.LocalizeDictionary.GetFullyQualifiedResourceKey(String key, DependencyObject target)
   at WPFLocalizeExtension.Extensions.LocExtension.FormatOutput(TargetInfo endPoint, TargetInfo info)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   at WPFLocalizeExtension.Extensions.LocExtension.ResourceChanged(DependencyObject sender, DictionaryEventArgs e)
   at WPFLocalizeExtension.Engine.LocalizeDictionary.DictionaryEvent.Invoke(DependencyObject sender, DictionaryEventArgs args)
   at WPFLocalizeExtension.Engine.LocalizeDictionary.set_Culture(CultureInfo value)
   at ABD.Localisation.Common.LocalisationServiceSingleton.ChangeLanguage(LanguageEnum language)
   at ABD.DBS.ViewModels.ShellViewModel.ChangeLanguage() in C:\Dev\driverlessbasestation\ABD.DBS.ViewModels\ShellViewModel.cs:line `

**Comment by konne** [comment] 2020-05-12 11:33
@AlastairCodd please provide a code example otherwise it is nearly impossible to find the root cause. I will close it.

**Closed by konne** 2020-05-12 11:33 UTC
